name: OKE-OIDC

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  oke-oidc:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Generate OIDC Token
        id: create-oidc-token
        run: |
          echo "Generating OIDC token..."
          ID_TOKEN=$(curl -s \
            -H "Authorization: Bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" \
            "$ACTIONS_ID_TOKEN_REQUEST_URL&audience=oke-kubernetes-cluster" | jq -r .value)
          echo "::add-mask::$ID_TOKEN"
          echo "id_token=$ID_TOKEN" >> $GITHUB_ENV

      - name: Configure kubectl
        run: |
          echo "Configuring kubectl..."
          echo $id_token > /tmp/token
          kubectl config set-cluster oke-cluster \
            --server=https://138.2.182.200:6443 \
            --insecure-skip-tls-verify
          kubectl config set-credentials github-actions \
            --token=$(cat /tmp/token)
          kubectl config set-context oke \
            --cluster=oke-cluster \
            --user=github-actions
          kubectl config use-context oke

      - name: Test Kubernetes Access
        run: |
          echo "Testing Kubernetes access..."
          kubectl get nodes
